server:
  port: 8802
spring:
  application:
    name: USER
  zipkin:
    base-url: http://localhost:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    nacos:
      discovery:
        service: ${spring.application.name}
      server-addr: localhost:8848

